spring.datasource.url=jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=*1992%A1i9b292$

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

#spring.jackson.property-naming-strategy=SNAKE_CASE

#CONFIGURACOES PARA O ARMAZENAMENTO DE FOTOS
# Local para definir o local onde as fotos serao armazenadas (diretorio local ou S3)
# ais.io.storage.tipo: aqui eu seleciono o tipo de armazenamento (local ou s3)
ais.io.storage.tipo=s3
ais.io.storage.local.diretorio-fotos=/Users/Augusto/Desktop/Augusto/Imagens/catalago
ais.io.storage.s3.id-chave-acesso=AKIAUQMJWREJLNPZPV7R
ais.io.storage.s3.chave-acesso-secreta=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
ais.io.storage.s3.bucket=ais.io-delivery
ais.io.storage.s3.regiao=us-east-2
ais.io.storage.s3.diretorio-fotos=catalago

#CONFIGURACOES PARA O SERVICO DE EMAIL
# algafood.email.impl: aqui eu seleciono o tipo de implementacao do envio de email (SMTP, FAKE, SANDBOX)
#algafood.email.impl=smtp
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
ais.io.email.remetente=AlgaFood <augusto.iseppe@gmail.com>
spring.freemarker.settings.locale=pt_BR
algafood.email.sandbox.destinatario=teste@algafood.com.br




